# Generated by Django 4.2 on 2025-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('location', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=125)),
                ('status', models.CharField(choices=[('Panding', 'Panding'), ('Successfull', 'Successfull')], max_length=123)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
