# Generated by Django 4.2 on 2025-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameramanagement',
            name='status',
            field=models.CharField(choices=[('Successfull', 'Successfull'), ('Panding', 'Panding')], max_length=123),
        ),
    ]
